log_dir: "./experiments/kmflow_re1000_rs256_ddim_log"

data:
    dataset: "kmflow"
    category: "kmflow"
    image_size: 256
    channels: 3
    num_workers: 4
    data_dir: "./data/kf_2d_re1000_256_40seed.npy"
    sample_data_dir: "./data/kmflow_sampled_data_irregnew.npz"
    stat_path: "./pretrained_weights/km256_stats.npz"
    # data_kw: 'u3232_nearest' #origin setting, but not work
    # data_kw: 'u3232' #fisrt try, work, but not good
    # data_kw: 'idx_1st' #second try, not work
    smoothing: False
    smoothing_scale: 5
    #kmflow_sampled_data_irregnew.npz has two npy files, u3232 and idx_1st, but idx_1st is not work
model:
    type: "simple"
    in_channels: 3
    out_ch: 3
    ch: 64
    ch_mult: [ 1, 1, 1, 2 ]
    num_res_blocks: 1
    attn_resolutions: [ 16, ]
    dropout: 0.0
    var_type: fixedlarge
    ema_rate: 0.9999
    ema: True
    resamp_with_conv: True
    ckpt_path: "./pretrained_weights/baseline_ckpt.pth"

diffusion:
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 1000

sampling:
    batch_size: 20
    last_only: True
    lambda_: 0.
    log_loss: True
    dump_arr: True